const carsData = [{
        date: "09-Mar-2022",
        carname: "Ford Ranger",
        reviews: 203,
        image: "https://picsum.photos/id/111/200/150",
        mileage: "45000 KM",
        location: "Delhi",
        engine: "3.5 diesel",
        transmission: "Machine",
        type: "Sedan",
        price: "Rs.100000",
      },
      {
        date: "11-Aug-2022",
        carname: "Mustang GT",
        reviews: 278,
        image: "https://picsum.photos/id/133/200/150",
        mileage: "33000 KM",
        location: "Delhi",
        engine: "2.2 petrol",
        transmission: "Machine",
        type: "SUV",
        price: "Rs.970000",
      },
      {
        date: "02-Jun-2021",
        carname: "BMW X7",
        reviews: 91,
        image: "https://picsum.photos/id/183/200/150",
        mileage: "59000 KM",
        location: "Mumbai",
        engine: "3.5 diesel",
        transmission: "Machine",
        type: "Sedan",
        price: "Rs.550000",
      },
      {
        date: "22-Jan-2019",
        carname: "Honda CR-V",
        reviews: 312,
        image: "https://picsum.photos/id/514/200/150",
        mileage: "21000 KM",
        location: "Bangaluru",
        engine: "2.2 petrol",
        transmission: "Machine",
        type: "MUV",
        price: "Rs.110000",
      },
      {
        date: "02-Jun-2021",
        carname: "Audi TT",
        reviews: 91,
        image: "https://picsum.photos/id/655/200/150",
        mileage: "21000 KM",
        location: "Mumbai",
        engine: "3.5 dies",
        transmission: "Machine",
        type: "Sedan",
        price: "Rs.130000",
      },
      {
        date: "22-Jan-2019",
        carname: "Honda CR-V",
        reviews: 312,
        image: "https://picsum.photos/id/514/200/150",
        mileage: "21000 KM",
        location: "Bangaluru",
        engine: "2.2 petrol",
        transmission: "Machine",
        type: "MUV",
        price: "Rs.110000",
      },
      {
        date: "02-Jun-2021",
        carname: "Audi TT",
        reviews: 91,
        image: "https://picsum.photos/id/655/200/150",
        mileage: "21000 KM",
        location: "Mumbai",
        engine: "3.5 diesel",
        transmission: "Machine",
        type: "Sedan",
        price: "Rs.130000",
      },
      {
        date: "22-Jan-2019",
        carname: "Ford Explorer",
        reviews: 312,
        image: "https://picsum.photos/id/1071/200/150",
        mileage: "10000 KM",
        location: "Bangaluru",
        engine: "2.2 petrol",
        transmission: "Machine",
        type: "Sedan",
        price: "Rs.180000",
      },
      {
        date: "02-Jun-2021",
        carname: "Audi TT",
        reviews: 91,
        image: "https://picsum.photos/id/45/200/150",
        mileage: "21000 KM",
        location: "Mumbai",
        engine: "3.5 diesel",
        transmission: "Machine",
        type: "Sedan",
        price: "Rs.150000",
      },
      {
        date: "22-Jan-2019",
        carname: "Ford Explorer",
        reviews: 312,
        image: "https://picsum.photos/id/146/200/150",
        mileage: "10000 KM",
        location: "Bangaluru",
        engine: "2.2 petrol",
        transmission: "Machine",
        type: "Sedan",
        price: "Rs.130000",
      }
    ];

    export default carsData;